### ISSUE TITLE
Brisk menu cannot find items/applications from Control Center

### ISSUE THREAD

**Issue by ThanosApostolou** [solus-project/brisk-menu#10]
Brisk menu cannot find with search applications like "Appearance", "Startup Applications", "MATE Tweak" and other items that exist on control center.

So, maybe add a "Settings" category or make the "Control Center" entry expandable or something so that brisk menu will be able to search and find these items.

**Comment by ikeydoherty** [comment]
That's why it has a Control Center on the sidebar. It only loads `mate-applications.menu`. Those apps come from another menu definition.

**Comment by ThanosApostolou** [comment]
Can you make this happen? Because I open 99% of my applications using menu and it's a matter of speed. For example with the advanced mate menu, I press "superkey", then I type "appe" and click enter and I open "Appearance" application in 0.5 sec without using any mouse. Especially after you have made brisk menu to work with "superkey", then it would be super fast if I don't need to use the mouse or anything to open Control Center and then choose the application I want.

**Comment by utybo** [comment]
I second this. Apps like Mate Tweak in Ubuntu MATE cannot be accessed through the search bar because of this. Is a "Preferences" category technically possible?

**Comment by flexiondotorg** [comment]
@ikeydoherty I see this is approved :-) Just to add this has been regularly requested in the feedback I've had from Ubuntu MATE testers.

**Comment by ikeydoherty** [comment]
Pushing back to `0.4.0` to allow us to get the `0.3.0` fixes out first

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €200 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by ikeydoherty** [comment]
So do we want a separate menu root for control center or merge the entries into the root?

**Comment by flexiondotorg** [comment]
@ikeydoherty I think items from the Control Center to should be visible in the "All" category so that when searching/scrolling the relevant item can be seen their.

Additionally, an "Administration" and a "Preferences" category should be included among the existing categories in the left pane of Brisk for users wanting to navigate directly.

**Comment by ikeydoherty** [comment]
Merged root - ok that would fit nicely. I preemptively included root differentiation .. ^^

**Comment by ikeydoherty** [comment]
OK so on `backends` branch I now have this working.  However my problem is that the menu adds a buttload of more categories @flexiondotorg:
![screenshot from 2017-05-18 20-13-44](https://cloud.githubusercontent.com/assets/164489/26219371/a39c247a-3c06-11e7-9334-0294c7aa5005.png)

Any reason it needs to be all categories, as opposed to a single unified category for the CC?

**Comment by ikeydoherty** [comment]
Hm I guess I could rekerjigger it to only show sub menus ..

**Comment by ikeydoherty** [comment]
More like it

![screenshot from 2017-05-18 21-29-07](https://cloud.githubusercontent.com/assets/164489/26222229/23e30b30-3c11-11e7-8797-e0e3be14e60f.png)

**Comment by ikeydoherty** [comment]
^ Like that screenshot, except the categories list is properly sorted. Now implemented in git master

**Comment by flexiondotorg** [comment]
Thanks! €200 has been transferred to Solus via PayPal.

**Comment by ikeydoherty** [comment]
Much appreciated kind sir!
