### ISSUE TITLE
Centos 7 x86_64 compiling error

### ISSUE THREAD

**Issue by hardcorp74** [solus-project/brisk-menu#105]
Centos 7 x86_64 compiling error

Native dependency 'libmatepanelapplet-4.0' not found
Native dependency 'libmate-menu' not found

But have:
mate-menus-libs
libmate-menu.so.2()(64bit)

mate-panel-libs
libmate-panel-applet-4.so.1()(64bit)

Maybe need change dep?

**Comment by alunux** [comment]
You also need the *-devel packages.

**Comment by hardcorp74** [comment]
Thanks, now good ) I was wrong, I'm sorry )

**Comment by hardcorp74** [comment]
After default compiling have error:
/usr/libexec/brisk-menu

(brisk-menu:25287): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by hardcorp74** [comment]
ldd /usr/libexec/brisk-menu
	linux-vdso.so.1 =>  (0x00007ffd985fa000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f8808333000)
	libmate-menu.so.2 => /lib64/libmate-menu.so.2 (0x00007f880811d000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f8807d82000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f8807b31000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f88077f3000)
	libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007f8807507000)
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007f8806bf4000)
	libmate-panel-applet-4.so.1 => /lib64/libmate-panel-applet-4.so.1 (0x00007f88069e5000)
	libnotify.so.4 => /lib64/libnotify.so.4 (0x00007f88067dd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8806410000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f88061ae000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8805f92000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f8805d8a000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f8805b86000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8805982000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f880576c000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f8805545000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f880532c000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f88050ea000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8804ed4000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f8804cac000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f8804a9f000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f8804854000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f880462c000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007f8804423000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f88041e6000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f8803fe3000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f8803dd3000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f8803bc8000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f88039bd000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f88037ba000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f88035b7000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f88033b1000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f8803171000)
	libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007f8802f69000)
	libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007f8802d67000)
	libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007f8802b58000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f8802946000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f880261e000)
	libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007f8802329000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8802027000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f8801e1f000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007f8801bf9000)
	libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007f88019ca000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f88017b4000)
	libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00007f8801132000)
	libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00007f8800e71000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8808647000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f8800c32000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f8800a2d000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f8800829000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007f880061d000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f880041b000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f88001b8000)
	libfreetype.so.6 => /usr/lib64/freetype-infinality/libfreetype.so.6 (0x00007f87fff0b000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f87ffce0000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f87ffa37000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f87ff801000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f87ff5fd000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f87ff3ef000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f87ff1e4000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f87fef72000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f87fed48000)
	libatspi.so.0 => /lib64/libatspi.so.0 (0x00007f87feb18000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f87fe8c8000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f87fe69a000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007f87fe495000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f87fe293000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007f87fe090000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007f87fde88000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007f87fdc85000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007f87fda7e000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007f87fd87b000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00007f87fd66d000)
	libwayland-server.so.0 => /lib64/libwayland-server.so.0 (0x00007f87fd45a000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f87fd249000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f87fd019000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007f87fcdfe000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f87fcbf8000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f87fc9c7000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f87fc7c2000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f87fc59c000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f87fc387000)
	libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007f87fc106000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f87fbf01000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007f87fbcba000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f87fbab5000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007f87fb89d000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f87fb68d000)

**Comment by hardcorp74** [comment]
readelf -d /usr/libexec/brisk-menu | grep library
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmate-menu.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk-3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgtk-3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmate-panel-applet-4.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libnotify.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

**Comment by hardcorp74** [comment]
#95 
Maybe this issue related, because i cann't add applet after compiling too
