### ISSUE TITLE
Duplicate app launchers

### ISSUE THREAD

**Issue by mydegeneration** [solus-project/brisk-menu#11]
![screenshot at 2017-01-11 23-23-58](https://cloud.githubusercontent.com/assets/7192681/21876918/2d1ba9f2-d855-11e6-804d-ca99ebc65495.png)

Not sure if it's just a problem with Steam and Brisk Menu but if I look under /usr/share/applications there aren't any .desktop duplicate files.

This is on a clean install of Solus MATE.

**Comment by ikeydoherty** [comment]
It's because `mate-menus` allows them multiple categories. If you run `desktop-file-validate` on that file you'll get a warning about it being in multiple categories.

**Comment by ikeydoherty** [comment]
FWIW I am considering dropping `mate-menus`, and glib's `GDesktopAppInfo`.

**Comment by mydegeneration** [comment]
I can report the rest of the applications seem to work OK with the menu. It seems to only affect Steam.

**Comment by mydegeneration** [comment]
I removed "Network" under categories on both .desktop files. It's not an ideal workaround but w/e the bug is not that serious.

![screenshot at 2017-01-12 00-32-19](https://cloud.githubusercontent.com/assets/7192681/21878233/ddb7e4c0-d85e-11e6-887c-994521c878a0.png)

**Comment by ThanosApostolou** [comment]
Maybe you can filter it somehow when you do a search? The advanced mate menu (fork of mintmenu) shows steam at both **Games** and **Internet** categories, but when you search **steam**, it only shows it one time. Maybe sometimes it's useful to show an application in multiple categories, so I think it would be better not to remove this capability (if dropping `mate-menus` does that).

**Comment by ikeydoherty** [comment]
`mate-menus`, and the thing it is forked from, `gnome-menus`, make my life very difficult. I use both forms, one in Brisk Menu, one in Budgie Menu. Both are highly opinionated, refuse to load certain `.desktop` files, and are utter shite at reloading.

**Comment by ikeydoherty** [comment]
OK got a fix that doesn't involve fixing the world. We'll store a hit record hashtable within the context of the current search filter. If it contains anything for the current desktop ID (`steam.desktop`, for example) we just continue. Otherwise, we store it. When a search changes, empty the map.

**Comment by ikeydoherty** [comment]
Happy to report this is now fixed in e38ddcb9b41e08664d8baa423e8ed49ec733d848 :)
