### ISSUE TITLE
Invite Martin Wimpress as project admin

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#113]
I'd like to request that @ikeyd add me as an admin (or team member with write access) so that I can maintain this project, put together a new release and start to address the issue back log :smiley:

**Comment by ikeyd** [comment]
Apologies I have no access to old account. Suggesting that @getsolus org becomes new home.

**Comment by flexiondotorg** [comment]
Happy to have project ownership under @getsolus or bring it under the Ubuntu MATE project.

**Comment by ikeyd** [comment]
That's a decision that would fall under the purview of the Solus team I believe, however @cybre was doing some fantastic work with Brisk. Resolution is but a repo-upload away. Good luck going forward, Brisk has always benefited immensely from your input and support.

**Comment by flexiondotorg** [comment]
I'm just keen to find a way forward and one where @cybre is still happy to contribute. I'll wait for @getsolus to comment and see what they have to say.

**Comment by cybre** [comment]
I will gladly continue to contribute regardless of the organization.
