### ISSUE TITLE
[Feature Request] Update applications list on mouse-over event in category list

### ISSUE THREAD

**Issue by FlipvantSuydenvelt** [solus-project/brisk-menu#12]
Currently, the list of applications in any category updates only after a mouse click on that category. It'd be nice if the list would update immediately on the mouse hovering over a category. Thanks.

**Comment by ikeydoherty** [comment]
It's not event based as such - it should just be refiltered on change

**Comment by flexiondotorg** [comment]
This feature has been much requested during the testing of Ubuntu MATE 17.04, it essentially restores some feature parity with the original Menu Bar in MATE.

As discussed with @ikeydoherty Ubuntu MATE will transfer €150 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by ikeydoherty** [comment]
I misinterpreted this bug as being like #25 .. only just got it ..

**Comment by ikeydoherty** [comment]
This is now implemented in git. For this behaviour and for some of the other items, we are going to need to add a UI to control it.

The new `gsettings` key is `rollover-activate`

**Comment by flexiondotorg** [comment]
Thank you, money sent.
