### ISSUE TITLE
[Feature Request] Sort all applications alphabetically including lowercase items

### ISSUE THREAD

**Issue by BigDaddyonTech** [solus-project/brisk-menu#14]
![brisk menu ss](https://cloud.githubusercontent.com/assets/11983339/22027451/f3757740-dca1-11e6-80e8-512aa605cad7.png)

I notice that applications that start with a lowercase letter get sorted at the bottom of the menu. Can all items be listed in alphabetical order regardless of case sensitivity.

**Comment by ikeydoherty** [comment]
Working on this in unstable now

**Comment by ikeydoherty** [comment]
Resolved in unstable branch, will be in `0.3.0` release, thx!

![screenshot from 2017-01-18 02-23-01](https://cloud.githubusercontent.com/assets/164489/22048526/87c4a42e-dd25-11e6-9200-803f058333bb.png)
