### ISSUE TITLE
Need a bit of help.

### ISSUE THREAD

**Issue by Dark-Witcher** [solus-project/brisk-menu#15]
I know this isn't an actual issue, but I have no idea how to do this.
OS Version: Mint Mate 18.1
Mate Version: 1.16.0

I download the repo, extract it, run "./autogen.sh" and then "sudo make install" and I get missing packages on "./autogen.sh" and nothing to make on "sudo make install". Can somebody tell me how to install it?

**Comment by feskyde** [comment]
You need to install the following development packages:

- `libgtk-3-dev`
- `libmate-menu-dev`
- `libmate-panel-applet-dev`

**Comment by ikeydoherty** [comment]
Can we group all the exact buildreqs? Then we can add them to a wiki or the docs or something

**Comment by flexiondotorg** [comment]
Bear in mind Brisk Menu won't work in Mint 18.1 because MATE is built against GTK2+ in Mint 18.1 and you can't mix GTK2+ and GTK3+ toolkits in `mate-panel`.

**Comment by BigDaddyonTech** [comment]
The Same goes for Antergos Mate. It does not use GTK3 for some reason.

**Comment by ikeydoherty** [comment]
This issue kinda died so I've left a comment in the README about some minimum requirements.
