### ISSUE TITLE
Brisk context menu for launching a Menu Editor

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#16]
Please add a right click context menu to Brisk that expose the ability to launch a menu editor. MATE users expect this because the traditional menu had that capability going back to the GNOME2 days.

The default menu editor in MATE is Mozo, forked from Alacarte. However `mate-panel` will support Menulibre and fallback to Mozo, in the next stable release. See this upstream commit for the rationale:

  * https://github.com/mate-desktop/mate-panel/commit/a506150684ad2e71b1f70190ee70fe9eda7a4ba9

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €100 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by ikeydoherty** [comment]
This is now implemented in ebc8b143fa490eefbac70ddf27b3be1e80911818
I have some compiler warnings re: deprecations to cleanup, but it is verified as working.

**Comment by flexiondotorg** [comment]
Thank you, money sent.
