### ISSUE TITLE
Rebindable activation keyboard shortcut, including support for the Super key

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#17]
Please add the capability to rebind the key combination to activate Brisk Menu. 

More importantly for Ubuntu MATE users is that this keyboard shortcut also supports binding to the Super key _only_. But, if Brisk Menu activation is bound to the _only_ the Super key:

  * Other keyboard shortcuts that include the Super key should not be swallowed. (_As happens in MATE Menu_)
  * Launching another application with a keyboard shortcut that includes the Super key should not also activate Brisk Menu. (_As happens in Whisker Menu_)

Exposing this configuration via gsettings only is fine because adding a UI to configure Brisk is a separate Roadmap item :-)

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €400 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by flexiondotorg** [comment]
@ikeydoherty €400 has been transferred to Solus Project and additional €200 has been transferred to @vkareh for working on Super key in Brisk Menu and Super key fixes in MATE Menu.

**Comment by ikeydoherty** [comment]
Merci!

**Comment by vkareh** [comment]
Awesome, thanks! :)

**Comment by gps1539** [comment]
Can someone show how to turn off superkey = brisk menu 0.4, as it is borking several of my muscle memory short cuts, cheers.  I'm guessing it somewhere deep in gsettings

**Comment by markgalassi** [comment]
I definitely need to turn off the superkey binding: I use super+key a lot in compiz.  I'm having trouble finding a place to turn off its trapping by mate's menus.

**Comment by vkareh** [comment]
To change it, for example, to <kbd>Ctrl</kbd><kbd>F10</kbd>:

```bash
gsettings set com.solus-project.brisk-menu hot-key '<Ctrl>F10'
```
(The default is `'Super_L'`)

**Comment by tinchou** [comment]
Hi! I'm trying to bind Brisk to a combination of Super + D, but I'm unable to make it work. Ctrl + F10 
as @vkareh explains works just fine. This doesn't:

```bash
gsettings set com.solus-project.brisk-menu hot-key '<Super>D'
``

Any ideas? I'm on Ubuntu MATE 17.10 by the way. Thanks!

**Comment by antoniotrkdz** [comment]
@colltoaction, in case this is still compelling to you ( and others).
`Super(_L)` is also known as `mod4`, therefore this should work:
```shell
gsettings set com.solus-project.brisk-menu hot-key '<mod4>D'
```
