### ISSUE TITLE
[Enhancement] Option to have the search bar at bottom

### ISSUE THREAD

**Issue by Two-Tone** [solus-project/brisk-menu#2]
I prefer it on the bottom (like how it is on Windows) because then my eyes barely have to move from the location of the menu button.

**Comment by ikeydoherty** [comment]
Cheers for filing it :D

**Comment by Two-Tone** [comment]
No problem! I actually had the issue report already filled out before asking :P

**Comment by ikeydoherty** [comment]
Ah fair play :D

**Comment by flexiondotorg** [comment]
@ikeydoherty Only one person, other than myself, from the Ubuntu MATE testers requesting this. How are you planning to implement this?

  * Automatically place the search bar at the bottom when Brisk Menu is in a bottom aligned panel?
  * gsettings key that can be toggled?

Either work for me (personally). If not an automatic switch then what I plan to do is have MATE Tweak poke the appropriate gsettings key when the Redmond (Windows-like) panel layout is selected to align the search bar to to bottom and the inverse for the only layouts.

**Comment by ikeydoherty** [comment]
So this in itself brings up an interesting discussion @flexiondotorg.
For yourself it's very likely you're going to want to control elements of Brisk dynamically from the outside. However, typically, panel applets have their own unique instance configuration.

Would it be preferably to not have instance configuration, and instead use only a well known gsettings path?

**Comment by flexiondotorg** [comment]
Yes, I'd not considered the way panel objects work. I think having some known gsettings path would be good, which you already have for two settings. 

That said, if the search bar position changes dynamically based on the alignment of the parent panel, then I don't need to poke anything ☺️

**Comment by ikeydoherty** [comment]
Hint taken :D

**Comment by ikeydoherty** [comment]
Done. :)
