### ISSUE TITLE
No bash prompt in terminal

### ISSUE THREAD

**Issue by texstar** [solus-project/brisk-menu#21]
There is no bash prompt [tex@localhost ~]$ when launching a terminal (mate-terminal) from the brisk menu.

brisk-menu 0.3.0
mate 1.16.x

**Comment by texstar** [comment]
I traced this back to SDDM login to MATE that is causing no prompt from any terminal app when launched from the Brisk menu. Login with KDM and legacy GDM work. I have no idea why.

**Comment by tele1** [comment]
Paste output 
`echo $PATH`

**Comment by texstar** [comment]
I found that I need to add the following to $HOME/.bashrc to get a terminal prompt when mate-terminal, lx-terminal, konsole etc is launched from the brisk-menu after login from sddm.

export PS1="[\u@\h \W]\\$ "

**Comment by ikeydoherty** [comment]
So I mean are you sure this is actually Brisk menu specific..?

**Comment by tele1** [comment]
**texstar**   
Without  **_export PS1="[\u@\h \W]\$ "_** in $HOME/.bashrc
when you  launching a mate-terminal from  icon on desktop bash prompt exist ?

**Comment by texstar** [comment]
Ikey, it only happens when I run Brisk Menu. I'm just reporting what I see when trying Brisk on PCLinuxOS as a drop in replacement. I will look for changes I can make on my distribution to make it work better. Keep up the good work. Love the menu.

**Comment by flexiondotorg** [comment]
I can't reproduce this issue on Ubuntu MATE 17.04 which uses Brisk Menu 0.3.0 and LightDM 1.21.5.

**Comment by ikeydoherty** [comment]
@texstar you got an ISO I can play with to reproduce this?

**Comment by ikeydoherty** [comment]
OK well no feedback since January so .. closing..
