### ISSUE TITLE
Scrollbar doesn't work if the cursor is positioned outside it

### ISSUE THREAD

**Issue by feskyde** [solus-project/brisk-menu#23]
- OS: Solus 2017.01.01.0
- Brisk version: 0.3.0

Same behavior as the old Budgie 8 menu:

https://youtu.be/vkg_NTfL_N4

**Comment by ikeydoherty** [comment]
Yep, duplicate of #3

**Comment by feskyde** [comment]
Oh issues search why are you so broken? 😕

**Comment by ikeydoherty** [comment]
Yeah its.. meh.
