### ISSUE TITLE
Alternative to Brisk

### ISSUE THREAD

**Issue by cinnamoner** [solus-project/brisk-menu#24]
@ikeydoherty 
@flexiondotorg 
Would you consider this https://github.com/ukui/ukui-menu instead of Brisk? I like the Mate DE a lot. The only reason I've never adopted it was the lack of a good startmenu. I think Brisk is okay but the one developed by the Kylin guys is better. Seems there's a compatibility issue but nothing huge, probably. Thanks for reading through.

**Comment by ikeydoherty** [comment]
You're more than welcome to use ukui-menu if thats your thing. It's not going to change what I'm working on though

**Comment by cinnamoner** [comment]
@ikeydoherty Okay, I like your sticking with what you believe in. I perceive it as a quality.
