### ISSUE TITLE
brisk menu not inherit environments variables

### ISSUE THREAD

**Issue by mekatronik-achmadi** [solus-project/brisk-menu#28]
on my Arch Linux with MATE 1.18 already installed GTK-noCSD and qt5ct. By using script on /etc/profile.d/, the variabel environment i.e GTK_CSD=0 and QT_QPA_PLATFORMTHEME=qt5ct was set

But when launch Gthumb from Brisk-Menu , it still use CSD windowing. Same goes Virtualbox (qt5) not get native theme. It's like they not get GTK_CSD=0 nor QT_QPA_PLATFORMTHEME=qt5ct

Is there a way or workaround to make a program launched from Brisk-Menu get all environment variables??

**Comment by ikeydoherty** [comment]
Brisk is d-bus activated currently. I guess the only fix is for us to become an in-process widget so that
we inherit the mate-panel env vars. @flexiondotorg thoughts?

**Comment by mekatronik-achmadi** [comment]
I try force dbus inherit env vars using command "dbus-update-activation-environment --systemd --all --verbose"

from verbose message, I see env var  GTK_CSD=0 was set

But when launched Gthumb from Brisk-Menu, it still use CSD. (which means GThumb not get env var  GTK_CSD=0)

**Comment by ikeydoherty** [comment]
Brisk is *already running* - injecting the vars won't help at that point

**Comment by mekatronik-achmadi** [comment]
well, I found some trick or workaround for this.

Instead dbus start brisk directly, it start a bash script which in turn start brisk. But in script, I add some env vars sourcing before start brisk line

here I do:
1. I create a bash script (called my_fav_menu.sh) with following content

#!/bin/bash
source /etc/profile
/usr/lib/brisk-menu/brisk-menu

2. Make script executable and copy to /usr/bin

3. replace "Exec=/usr/lib/brisk-menu/brisk-menu" with "Exec=/usr/bin/my_fav_menu.sh"

4. re-login

It maybe need a little bit memory for script (around 4MB), but Brisk now can launch a program with env var I need

**Comment by mekatronik-achmadi** [comment]
So I updated to the latest release (0.4.0) and those tricks above doesn't work anymore

any word or suggestion?
