### ISSUE TITLE
Scroll bar gets stuck when scrolling

### ISSUE THREAD

**Issue by baimafeima** [solus-project/brisk-menu#31]
The scroll bar on the right side of Brisk Menu gets stuck when scrolling it. 

How to reproduce: 
Left click on the scroll bar and keep the button pressed **while** moving a pointing stick or mouse (in my case Lenovo TrackPoint) up or down.

**Comment by flexiondotorg** [comment]
Duplicate of  #3.

**Comment by ikeydoherty** [comment]
Ah yeah dupe ty :)
