### ISSUE TITLE
Innovate and unify menu main categories with those of the Software Center

### ISSUE THREAD

**Issue by baimafeima** [solus-project/brisk-menu#33]
Currently the menu main categories are as follows: 
- Accessories
- Education
- Games
- Graphics
- Internet
- Office
- Programming
- Sound & Video
- System Tools
- Universal Access

Do these follow the freedesktop.org specifications in some way? https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

I am not sure what is the best way to solve this but why not use them as a basic orientation but ultimately develop a more intuitive categorization system. I've never really been a fan of the freedesktop categories. They are neither efficient (in the sense of finding what I need) nor exploratory (in the sense of software discoverability) but simply a convention system some people thought made sense to them. 

Lastly, I think the categories should match those of the Software Center or vice versa.

**Comment by ikeydoherty** [comment]
These are defined by the freedesktop menu specification. To change them requires changing thousands of packages to support a new "standard". I can fix a lot of things - this isn't one of them :)
