### ISSUE TITLE
Expose a "dash" style menu when added to a vertical panel

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#36]
As discussed with @ikeydoherty briefly, a gsettings option will be added to Brisk to render something similar to how [Slingscold](https://sourceforge.net/projects/slingscold/) does so that applications are presented as large icons while retaining the search filter and category selection.

The reason for suggesting this feature is so Brisk can be used in as a pseudo replacement for the Unity dash in MATE.

**Comment by ikeydoherty** [comment]
Can I add a further couple subitems to this:

 - Dynamic switching between "ListBox" and "FlowBox"-esque modes (likely need a custom container truth be known)
 - Apply CSS classes depending on "mode" - allowing "creative themers to unlock the Brisk potential" (See I could totally work in marketing. Or bullshit)

**Comment by flexiondotorg** [comment]
I agree to the above, excepting for the marketing bullshit ;-)

**Comment by ikeydoherty** [comment]
:P

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €700 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by ikeydoherty** [comment]
Is this something you want to be full screen or resizable?

**Comment by flexiondotorg** [comment]
In my minds eye I imagined something full screen and not resizeable

**Comment by Xmetalfanx** [comment]
Sorry to but-in guys but would this be an option or the default behavior (say full screen dash when brisk is on a vertical menu)? ... I love the idea of an option for this for those that want it, but some users (cant say I'd NOT be one of them) may want a left hand panel with the brisk menu the way it is and not something full screen.

#myTwoCents

**Comment by ikeydoherty** [comment]
We'd have it be an option, much like how right now the menu adjusts the layout based on screen position, but in accordance with an automatic policy defined by our gsettings

**Comment by Xmetalfanx** [comment]
sounds great (@ it being an option)  .. I'd try it out but like I said not everyone is a fan of the full screen "dash"

**Comment by GNOME-IS-LIFE** [comment]
Sounds lit!!

**Comment by ikeydoherty** [comment]
killmenow.

**Comment by GNOME-IS-LIFE** [comment]
???

**Comment by ikeydoherty** [comment]
This is now implemented in git master by @cybre

**Comment by flexiondotorg** [comment]
Initial acceptance testing has been completed on Ubuntu MATE 18.04 daily. As agreed €700 has been sent to @cybre via PayPal. Thanks for all at Ubuntu MATE for your hard work!
