### ISSUE TITLE
GSettings option to display no text label

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#37]
In addition to #13 please add a gsettings option to disable the text label completely such that only the icon is displayed for Brisk Menu in the menubar.

**Comment by ikeydoherty** [comment]
In progress (pending Pringles top up, should be done in the next hour)

**Comment by ikeydoherty** [comment]
I am now a man of many pringles, let's go

**Comment by ikeydoherty** [comment]
Fixed in 38b37228e5fd6a9a716366af6f9ddc65732bd6c5 - with 24 minutes to go :P

**Comment by flexiondotorg** [comment]
Thanks! €100 has been transferred to Sous Project.
