### ISSUE TITLE
Empty categories should not be displayed 

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#39]
Some categories presented by Brisk Menu are empty, it would be preferable and consistent with the default MATE menu to not present any categories that are empty.

**Comment by ikeydoherty** [comment]
Lol good point xD

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €100 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

**Comment by ikeydoherty** [comment]
Fixed in 6e32db968a54f6f2cf0ce849f182b428b60b0771

**Comment by flexiondotorg** [comment]
Thanks! €100 has been transferred to Solus Project.

**Comment by ikeydoherty** [comment]
Merci! Solus appreciates your gratitude and support :D
