### ISSUE TITLE
Menu crashes after installation of a new application

### ISSUE THREAD

**Issue by mrferda** [solus-project/brisk-menu#4]
Hi, 

I had the brisk menu dump core.
I installed a new application (with a *.desktop flie in /usr/share/applications) and when I opened the menu immediately after that, the menu crashed.
I can upload the core file if it helps.

**Comment by ikeydoherty** [comment]
Need more details please, OS, version of Brisk, etc

**Comment by ikeydoherty** [comment]
Yeah probably good if you could get me the gdb backtrace, cheers

**Comment by mrferda** [comment]
It’s reproducible: every time a *.desktop file is added or removed, the menu has to be restarted.

**Comment by mrferda** [comment]
[bt.txt](https://github.com/solus-project/brisk-menu/files/687445/bt.txt)

**Comment by mrferda** [comment]
I fired up the Solus Mate ISO and had the same issue there: when I remove/add a *.desktop file, immediately open the menu and start typing, the menu crashes.
It's fine if you wait a second before opening the menu, so I assume the problem only exists while the cached list of applications is being updated (although I know nothing about how that works in detail).

[bt.txt](https://github.com/solus-project/brisk-menu/files/691100/bt.txt)

**Comment by ikeydoherty** [comment]
OK so we need to block all functions while updating then, should be easy enough

**Comment by ikeydoherty** [comment]
Pushing back to `0.4.0` to allow us to get the `0.3.0` fixes out first

**Comment by flexiondotorg** [comment]
@ikeydoherty Is this a duplicate of #25?

**Comment by ikeydoherty** [comment]
Related but not strictly a dupe. I suspect merging the patch would fix both though.

**Comment by ikeydoherty** [comment]
I believe this to be fixed in git master. If after `0.4.0` this persists for you, please re-open.
