### ISSUE TITLE
Make the menu auto size to match that of visible categories + favourites

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#40]
The categories in Brisk can end up requiring a scrollbar being required to see the full extent of the categories and favourites. Make the height of the menu dynamically calculated based on the sum of visible categories and favourites.

**Comment by ikeydoherty** [comment]
So we want to **ban** vertical scroll on sidebar list yeah?

**Comment by flexiondotorg** [comment]
Not an outright ban because on screens with limited vertical resolution and 12 favourites you'd need a scrollbar. The intent is to limit when a scrollbar is required.

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €100 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed. 

At @ikeydoherty's discretion this award can be paid to the developer landing an acceptable commit. If Make yourself known to `flexiondotorg' in the `#solus-dev` IRC channel so we can get find out what PayPal account to transfer the money to.

**Comment by flexiondotorg** [comment]
Thanks! €100 ($108) has been transferred to @cybre for working on this issue.
