### ISSUE TITLE
SuperKey to escape from MENU

### ISSUE THREAD

**Issue by bogdanke8** [solus-project/brisk-menu#42]
Now on Ubuntu Mate 17.04 it's possible to use SuperKEY to use the Brisk Menu. It's posible that when SuperKEY is pressed and the Menu apear if I press SuperKEY again the Menu to disapear?... At this moment I need to press ESC not SuperKEY to exit from Menu from shortcuts.

Resume: 
- accesing and exiting Brisk Menu NOW: SuperKEY+ESC
- accesing and exiting Brisk Menu IN THE FUTURE: SuperKEY+SuperKEY

**Comment by flexiondotorg** [comment]
I'd like to clarify this request, the defined hot-key should activate and dismiss the Brisk Menu. Using ESC to dismiss the menu should also remain.

**Comment by bogdanke8** [comment]
Exactly, it's perfect to have ESC to exit, but should also be usefull to have SuperKEY for this option...

**Comment by ikeydoherty** [comment]
Fixed in 11e1f95e7619b6e9f17eec8c9c8c13076bf18632

**Comment by bogdanke8** [comment]
Wow, how fast you solved this issue! Great!

**Comment by cinnamoner** [comment]
@ikeydoherty Thanks. The fix is only logical.
