### ISSUE TITLE
Up and down arrow key movement makes font disappear

### ISSUE THREAD

**Issue by baimafeima** [solus-project/brisk-menu#46]
When moving through brisk with the arrow keys (up/down) the font next to the icons disappears. The default behavior should be identical when browsing the categories with a mouse or a track point.

**Comment by Xmetalfanx** [comment]
I am seeing this too ... may be a "white text on white background" sort of thing but using the arrow keys I see this as well

**Comment by Xmetalfanx** [comment]
Update: On Ubuntu Mate at the moment ... I can't remember right off hand what GTK theme I am using but I do not see this at the moment ... no matter the distro (even Ubuntu Mate or Solus Mate) ... this may be related to something in the theme you're using
