### ISSUE TITLE
Superkey to close Brisk Menu not working for me

### ISSUE THREAD

**Issue by Xmetalfanx** [solus-project/brisk-menu#47]
Decided to make this one request instead of two 

A) Hover over (?? option?.... default action?)  where instead of going over the categories if your using a mouse and then having to click the category to see the apps in it ... just hovering over the category brings up that specific categories apps 

Wow I said categories alot there

B) While I love the superkey to open feature, If i accidentally hit the superkey i have to hit escape to close the menu .... perhaps maybe "If the brisk menu is open, and the super key is hit again, close the brisk menu"  sort of thing... minor thought but it is a thought

**Comment by ikeydoherty** [comment]
for A) There is already a gsetting for this:

```
gsettings set com.solus-project.brisk-menu rollover-activate true
```

For B - it is actually working on my system, so we'll need to debug wtf is going on there.

**Comment by bmeznarsic** [comment]
Did you push *all* of the commits? :P

**Comment by ikeydoherty** [comment]
Yes :P

**Comment by Xmetalfanx** [comment]
I have been busy today and not booted into Solus yet ... dealing with getting a full refund on my (2016 to 2017 main system) and looking for a replacement.

I will go into Solus and see if its working now (the super key thing) ... maybe a logout and logn thing "fixed it for me" lol ... I will post back with any updates.

**Comment by Xmetalfanx** [comment]
ok I am not sure what command to run or log file may be needed to bugfix this ... heck if other Solus Mate users are not having this issue maybe something funky happened to this install, specific to my end and not something in Solus Mate itself

other than the brisk menu not closing (after superkey or anything opens it) is the only issue with it that I am having

**Comment by Xmetalfanx** [comment]
Didn't wait for an answer ... reinstalled ... did all the updates ... closing and opening the menu works perfectly fine now ... now sure what happened to that last (@ 2 weeks old? installation) 

Closing this issue as it was probably just a borked install or some other fishiness
