### ISSUE TITLE
always focus text field when opening menu

### ISSUE THREAD

**Issue by mrferda** [solus-project/brisk-menu#5]
if you open the menu, use the arrow keys to navigate to an item and then open the menu for a second time, focus is on the application list and you have to tab back to the text field to type.

**Comment by flexiondotorg** [comment]
@ikeydoherty I've had this feedback from Ubuntu MATE testers, great to see you've approved it :-)

**Comment by ikeydoherty** [comment]
Fixed in 60baf74c6a73d9d9dbd820c75b079b6d20ac407c
