### ISSUE TITLE
Vertical Panel Aesthetic

### ISSUE THREAD

**Issue by BigDaddyonTech** [solus-project/brisk-menu#50]
I am using the brisk menu on a vertical panel and it shows the menu lower than the icon, almost like it should appear on a horizontal panel. 

For a vertical panel, I think the menu should start at the top of the icon but out to the right side of it so not to cover the panel itself but also cover the open space to the right of the button under the top panel.

![briskmenu](https://cloud.githubusercontent.com/assets/11983339/26264004/1be0141c-3ca9-11e7-9536-6dec102ee717.png)

**Comment by ikeydoherty** [comment]
Yep the menu should ideally appear in line with the button flush to the right edge
