### ISSUE TITLE
Require permission to alter license headers in the Brisk Project

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/brisk-menu#53]
We have a bit of a weird situation going on with our "Copyright" strings in files, where one bit gets copied to another file, and the original copyright assignment is not quite preserved.

**Proposal:**

Collective copyright assignment to "The Brisk Menu Developers", i.e.

_Copyright 2016-2017 Brisk Menu Developers_

And an `AUTHORS` file to list contributors.

**Sign Offs**:

I'd need sign off from the following contributors to allow this to happen:

 - [x] @flexiondotorg
 - [x] @vkareh 
 - [x] @cybre 
 - [x] @feddasch 
 - [x] @ikeydoherty

**Comment by ikeydoherty** [comment]
_I hereby consent to my contribution copyright assignment being altered to a project wide collective for the entire duration of the project_

**Comment by cybre** [comment]
I hereby consent to my contribution copyright assignment being altered to a project-wide collective for the entire duration of the project.

**Comment by vkareh** [comment]
I hereby consent to my contribution copyright assignment being altered to a project wide collective for the entire duration of the project

**Comment by flexiondotorg** [comment]
I hereby consent to my contribution copyright assignment being altered to a project wide collective for the entire duration of the project.

**Comment by feddasch** [comment]
I hereby consent to my contribution copyright assignment being altered to a project-wide collective for the entire duration of the project.

**Comment by ikeydoherty** [comment]
Added an about dialog in https://github.com/solus-project/brisk-menu/commit/1dcda2cb0ce1b68c0e2b7ac385fafe370fa94610

**Comment by ikeydoherty** [comment]
Cheers all
