### ISSUE TITLE
Default string for the label is '' but shows as Menu in the panel.

### ISSUE THREAD

**Issue by uts-c3** [solus-project/brisk-menu#56]
Hi there,
I just tried to get rid of the Menu label on the panel and found that when you leave the default string, which is '' or you change the custom value to '', you still see the Menu word in the panel. The workaround was to change the value to space.

Cheers

PS: hope this is the right place to report issues

**Comment by ikeydoherty** [comment]
This is the intended behaviour. If you want to hide the label, you must set the `label-visible` key to false.
