### ISSUE TITLE
Unable to close Brisk with second Super_L keypress

### ISSUE THREAD

**Issue by nooryani84** [solus-project/brisk-menu#58]
The initial Super_L to open the Brisk menu is successful, but pressing Super_L a second time doesn't close it.   Is this intended behaviour?

On a somewhat unrelated note, is it possible to change the keybinding if I for instance wanted to bind Super_L to Albert / Synapse?

Thank you for this brilliant menu, the new update which populates the menu with stuff from Control Center is great! :)

Edit:  I forgot to mention that I'm using Ubuntu Mate 17.04 with Martin Wimpress' PPA https://launchpad.net/~flexiondotorg/+archive/ubuntu/brisk-menu

**Comment by Xmetalfanx** [comment]
ah ... that is different with it being Ubuntu Mate vs my issue ... not sure if Ikey told/let Martin know about this but there was something that Ikey did to push a Mate-desktop update out in Solus Mate's TESTING BRANCH (and yes i know its a diferent distro) .. the change DID fix the issue

**Comment by nooryani84** [comment]
@Xmetalfanx Yea, I found out how to change the hotkey.   Haven't been able to close the Brisk menu using Super_L though.

**Comment by nooryani84** [comment]
It works fine when I build it from the source file: https://codeload.github.com/solus-project/brisk-menu/zip/v0.4.0

Sorry about that, the problem is only present when I use the package from Martin's PPA and not when I build from source.   Should I close it since this is an issue with the build in the PPA and not the source?

**Comment by ikeydoherty** [comment]
Hm lets see what @flexiondotorg finds!

**Comment by nooryani84** [comment]
Ok.  I don't quite know what I did the first time, and I should have tested it on a clean system again before reporting the bug.  I just checked on a clean install and it DOES work with Martin's PPA.

I am very sorry for wasting everyone's time, this all boils down to my stupid user error.
