### ISSUE TITLE
[Feature Request] Add internationalisation

### ISSUE THREAD

**Issue by mrferda** [solus-project/brisk-menu#6]
For a consistent desktop experience multi language support would be nice.

**Comment by ikeydoherty** [comment]
Yep

**Comment by mrferda** [comment]
Since the xfce whisker menu is very similar maybe [this](https://github.com/gottcode/xfce4-whiskermenu-plugin/tree/master/po) could save some work.

**Comment by ikeydoherty** [comment]
Solus is setup on Transifex and that's where we handle translations on all of our projects.  I've no interest in just lifting stuff from other people's repos, that's how you do a piss poor job of anything :)

**Comment by ikeydoherty** [comment]
OK well it's translatable now

**Comment by ikeydoherty** [comment]
Oh. should point to the where: https://www.transifex.com/solus-project/brisk-menu/
