### ISSUE TITLE
[Feature Request] Dynamic priority list of All Apps (see Budgie menu)

### ISSUE THREAD

**Issue by gjsa73** [solus-project/brisk-menu#60]
Budgie Desktop menu has an awesome feature that reorders the apps listed by default according to usage.

So when clicking the Brisk menu button, the apps listed under "All" would be ordered according to most often used.  This feature basically makes redundant having to choose favourites.

**Comment by ikeydoherty** [comment]
It's actually broken completely in Budgie, and only exists because Budgie Menu is incapable of proper search sorting, whereas Brisk is. Brisk instead will have a Favourites menu and sane search sorting

**Comment by ikeydoherty** [comment]
Update: I'm also removing this behaviour from Budgie because it's completely crippled and is only present to compensate for a lack of real sort behaviour. This won't be coming into Brisk and derping it up. We'll have a proper favourites support for priority items.
