### ISSUE TITLE
'Edit Menus' context entry doesnt do anything

### ISSUE THREAD

**Issue by philipzae** [solus-project/brisk-menu#62]
So menulibre isnt installed by default on Solus Mate, so when i right-clicked on the Brisk-Menu button and clicked 'Edit Menus', nothing happened. Atleast an error message should appear stating that a menu editor needs to be installed and possibly also lead the user to get it installed in the software center or GUI package manager.

**Comment by ikeydoherty** [comment]
![screenshot from 2017-08-22 17-11-12](https://user-images.githubusercontent.com/164489/29575780-72be76ee-875d-11e7-9efd-4350dd2a7e4f.png)

**Comment by ikeydoherty** [comment]
Also treated in Solus: https://dev.solus-project.com/rIMGMa10f6a13a7b8be96be21b95a87bebcb702756ff7
