### ISSUE TITLE
Move frequently searched items to top?

### ISSUE THREAD

**Issue by orschiro** [solus-project/brisk-menu#64]
Possibly related to the favorites discussion here https://github.com/solus-project/brisk-menu/issues/8.

What do you think of the idea that frequently searched terms move up to the top?

Example: You constantly search for "libre".

This brings up the whole suite. But you always select "Writer".

This would move writer to the top so that just by typing "libre", you could launch writer. :-)

**Comment by ikeydoherty** [comment]
We know how badly that goes, it was the single-most hated feature in Budgie Menu. That's why we have term-relevancy instead. I'd rather we focus on improving the lexical score than having hard-pinned priorities.
