### ISSUE TITLE
Change translation "da_DK" to "da"

### ISSUE THREAD

**Issue by scootergrisen** [solus-project/brisk-menu#65]
Can we can danish translation from "da_DK" to just "da".

**Comment by ikeydoherty** [comment]
I get asked this on basically every project I do :) I only accept the translations and teams that people request and translate. And they keep doing it for all of them, so obviously someone needs them, otherwise it wouldn't be created. Closing as a non-issue.

**Comment by scootergrisen** [comment]
Maybe there is a reason why people request it.

**Comment by ikeydoherty** [comment]
They request both things, I'm the one who sees both sides of the coin. :)
