### ISSUE TITLE
Nitpick Design: space to the left of search text

### ISSUE THREAD

**Issue by epgfm** [solus-project/brisk-menu#68]
There should be some padding between the magnifying glass and the search text "ter" in the image below.
![screenshot at 2017-08-16 10 43 42](https://user-images.githubusercontent.com/10635269/29355123-14b03bc4-8270-11e7-9a2c-288059994b74.png)

**Comment by ikeydoherty** [comment]
That's down to the theme I'm afraid, nothing to do with Brisk itself.

**Comment by ikeydoherty** [comment]
Gonna close this but gonna ping @flexiondotorg @raveit65 so they're aware of the theming issue on Ubuntu MATE
