### ISSUE TITLE
Invisible Brisk Menu when edited

### ISSUE THREAD

**Issue by paulomagnum** [solus-project/brisk-menu#78]
Whenever I try to edit the brisk menu via mozo, it's applet becomes invisible in the mate-panel. I can still open the menu when I press the super key tho. See: [brisk menu screenshots.zip](https://github.com/solus-project/brisk-menu/files/1619981/brisk.menu.screenshots.zip)

How to reproduce:
1. Right-click the brisk menu applet.
2. Click edit menus.
3. Brisk menu applet will be gone.

Workaround:
Running "pkill mate-panel" on the terminal will bring back the applet.

System details:
brisk-menu 0.5.0-1
mate-panel 1.18.6-1
mate-desktop 1.18.0-1
linux 4.14.12-1
OS: Archlinux

Please let me know if you need any additional info. Thank you.

**Comment by ikeydoherty** [comment]
Fixed in git master
