### ISSUE TITLE
Add Favourites Support

### ISSUE THREAD

**Issue by Apolo2025** [solus-project/brisk-menu#8]
Hello,

It would be great if the Brisk Menu could have a favorites menu and an option to be able to right click on any program and add it to that favorites menu,

Thank you,

EastAPOLO

**Comment by ikeydoherty** [comment]
Yup this is planned after 0.3

**Comment by ikeydoherty** [comment]
Renamed this because I can never bloody see it in the list :P

**Comment by flexiondotorg** [comment]
As discussed with @ikeydoherty Ubuntu MATE will transfer €200 to the Solus Project (via PayPal) when commit(s) implementing this feature land and the issue closed.

At @ikeydoherty's discretion this award can be paid to the developer landing an acceptable commit. Make yourself known to `flexiondotorg` in the `#solus-dev` IRC channel so we can get find out what PayPal account to transfer the money to.

**Comment by flexiondotorg** [comment]
Funds transferred to @cybre.
