### ISSUE TITLE
[Feature Request] Enable using brisk-menu with the tint2 panel

### ISSUE THREAD

**Issue by danboid** [solus-project/brisk-menu#81]
I'm sure I heard Ikey say that brisk was designed to be a universal X menu app so to that end I would like to be able to use brisk as my menu with the tint2 panel. tint2 doesn't feature its own intregrated menu so I am currently using pmenu:

https://gitlab.com/o9000/pmenu

I following the instructions here to configure pmenu for use with tint2:

https://gitlab.com/o9000/tint2/wikis/ThirdPartyApplets

I would prefer to use brisk because pmenu is GTK2 and it also lacks a search feature like brisk has however I have tried running brisk-menu under openbox/tint2 and no menu gets displayed.

Maybe this will require some hacking on or opening a feature request for tint2 too, I'm not sure.

Thanks

**Comment by ikeydoherty** [comment]
No I said that Brisk is distro agnostic, not desktop agnostic. It is a menu for the MATE Desktop.

**Comment by danboid** [comment]
Smells like a "won't add" to me, ah well.

The reason I ask is it turns out that tint2 now has better HiDPI support than everything bar maybe Unity so it would be great to have a better menu.

Have you tried tint2 recently/ever?

**Comment by ikeydoherty** [comment]
> Smells like a "won't add" to me, ah well.

It's a menu for mate, I don't know what you want me to say there. It requires knowing stuff about the running panel such as orientation, position, button anchoring, etc. Having it randomly executed as a command (and no lifetime management) by tint2 removes all of that, it wouldn't know where it was meant to be.

> The reason I ask is it turns out that tint2 now has better HiDPI support than everything bar maybe Unity so it would be great to have a better menu.

Eh, Unity was/is a full desktop. tint2 is just a panel.

> Have you tried tint2 recently/ever?

Yes, I used to use it exclusively with openbox.

**Comment by danboid** [comment]
I have recently reassessed all Linux desktops and WMs (inc KDE, MATE, Budgie, Enlightenment, Pantheon, GNOME 3, XFCE and others) for their 4K friendliness and the best option for me now is tint2. Yes, I know its not a complete DE but it can be tweaked to do everything the full fat DEs can do, regarding the functionality that I actually need.

I have been using MATE as my main DE for the last few years but its handling of multiple displays and DPIs is quite poor. You can only scale the panel by 2X at login time only using an env var and if you try having a panel on multiple displays, all sorts or crappiness ensues when you unplug one of your displays.

tint2 git has recently introduced two new config options, scale_relative_to_screen_height and scale_relative_to_dpi which have solved my panel / display / DPI issues better than any other Linux desktop/WM. I never liked Unity, despite its good display support.

**Comment by ikeydoherty** [comment]
OK but you *do realise* that you're approaching a project that is entirely unrelated to your desktop of choice and effectively trying to convert me to your new religion, right?

**Comment by danboid** [comment]
Haha! Great response Ikey!

I'm listening to the latest Linux Unplugged where Wimpy explained the upcoming HiDPI improvements in the new MATE release and it sounds as if the next MATE could equal or surpass Unity for HiDPI support BUT it will require compiz to achieve that. I may be willing to put up with that if it works as well as he promises but I must admit I still prefer the non-composited DEs/WMs. I also wonder if the overlapping panel issue has been fixed as part of this?

Thanks for your feedback, it is much appreciated!

**Comment by ikeydoherty** [comment]
I totally get that fwiw - and yeah @flexiondotorg also let me know that MATE HiDPI support is about to improve considerably.

FWIW my biggest objection in implementing this support is basically as follows:

 - Whatever you do, Brisk is going to depend on parts of GNOME/MATE stacks and isn't an appropriate "true lightweight" solution for Openbox setups
 - Trying to communicate intent from tint2, "run this process", doesn't give Brisk nearly enough information to operate. It basically needs a real button for relative screen placement, otherwise we go down the road of nasty CLI options, `--appear-at-mouse-x-y --x-offset 6` style jank :/

**Comment by danboid** [comment]
I didn't think brisk was so dependent upon MATE - I presumed it was going to be more or less a regular GTK, can run under any X WM affair. The MATE dependency is indeed very much a showstopper for my suggestion.

Thanks again Ikey!

**Comment by ikeydoherty** [comment]
Yer - I mean the core part is very much decoupled but the backend portion for .desktop files relies on mate-menus library, which is gonna need some MATE specific bits, and then you get up into gtk/gvfs land.. etc.. :)
