### ISSUE TITLE
Dash window-type ignores CSS class styling

### ISSUE THREAD

**Issue by flexiondotorg** [solus-project/brisk-menu#82]
When using the Dash window type it is not possible to style it. This is an issue because the default use of  `theme-bg-color` cause the Dash window to be unreadable with some themes, such as Ambiant-MATE the default theme on Ubuntu MATE.

**Comment by flexiondotorg** [comment]
@cybre @ikeydoherty Any chance this can get some attention please?

**Comment by cybre** [comment]
Yes. I'll be done with exams after tomorrow so I can work on this.

**Comment by cybre** [comment]
@ikeydoherty feel free to assign this to me.

**Comment by flexiondotorg** [comment]
_Blows on mic._

"Is this thing on?" :wink:

**Comment by cybre** [comment]
Sorry man. I'm visiting family (didn't plan this). I'll be back home tomorrow. I'll bug you on telegram.
