### ISSUE TITLE
Brisk Menu doesn't show some icons

### ISSUE THREAD

**Issue by ThanosApostolou** [solus-project/brisk-menu#9]
Brisk menu doesn't show some icons, whereas the advanced mate menu shows theme normally. I tried with different icon themes but the problem presists. I am on Manjaro MATE edition. See images below:
http://imgur.com/a/UOQnN
http://imgur.com/a/GewvB

**Comment by ThanosApostolou** [comment]
I noticed that the icons aren't shown at the applications `skype` and `winusb` which both are installed from AUR and the icon entries are `Icon=skype.png` and `Icon=winusbgui-icon.png` respectively. So, maybe it has something to do with the `.png` suffix. Maybe that helps a bit.

**Comment by ikeydoherty** [comment]
Where is `skype.png` located? I'll need to recreate the conditions

**Comment by ikeydoherty** [comment]
(I would assume `/usr/share/pixmaps` ?)

**Comment by ThanosApostolou** [comment]
Correct the icons are at `/usr/share/pixmaps`. I noticed also that if I edit the `/usr/share/applications/skype.desktop` and change the line `Icon=skype.png` to `Icon=skype`, then the icon is shown properly.

**Comment by ikeydoherty** [comment]
Gotcha. I have a fix in mind, thanks :)

**Comment by ThanosApostolou** [comment]
Glad I could help 😃

**Comment by ikeydoherty** [comment]
This is now resolved in 2cfea90fc6db86c70605bdaffc6e40104671ea42 :)
