### ISSUE TITLE
brisk-menu crashed with SIGSEGV in gtk_list_box_insert()

### ISSUE THREAD

**Issue by o-alquimista** [solus-project/brisk-menu#98]
The menu crashes often when simply scrolling through the entries, usually happens more when I move the mouse over the categories. The default behavior in Ubuntu MATE 18.04 is to activate the category on mouse-over.

Ubuntu asks me to send a report afterwards. I'll provide you with some details. This is all I know how to collect.

```
Version "mate-applet-brisk-menu 0.5.0-7ubuntu1"

brisk-menu crashed with SIGSEGV in gtk_list_box_insert()

kernel: [ 6584.855634] brisk-menu[2356]: segfault at 7fc1375e2990 ip 00007fc1375e2990 sp 00007ffd0eee2098 error 15 in libgtk-3.so.0.2200.30[7fc1375dd000+7000]
```

**Comment by flexiondotorg** [comment]
This is the biggest Brisk Menu crasher on Ubuntu MATE 18.04 and newer. Here's the bugs with plenty of duplicates for analysis:

  * https://bugs.launchpad.net/ubuntu/+source/brisk-menu/+bug/1764566
